### ISSUE TITLE
Plugin can't be loaded error

### ISSUE THREAD

**Issue by jpl-ivengi** [Gerrit0/typedoc-plugin-missing-exports#1]
The NPM package seems to be broken due to the missing dist folder?

After running  `npm install typedoc-plugin-missing-exports -D` and then running typedoc I get the following error:

```
Error: The plugin typedoc-plugin-missing-exports could not be loaded.
Error: Error: Cannot find module '<<path-to-project>>\node_modules\typedoc-plugin-missing-exports\dist\index.js'. Please verify that the package.json has a valid "main" entry
```

This is with the latest version of typedoc and this plugin.

**Comment by Gerrit0** [comment]
Shoot, sorry about that! Not entirely sure how I messed that up...

**Comment by jpl-ivengi** [comment]
Thanks for the quick response and fix!
