### ISSUE TITLE
Show type parameters

### ISSUE THREAD

**Issue by thelinuxlich** [Gerrit0/typedoc-plugin-missing-exports#11]
I'm currently getting this:

![image](https://user-images.githubusercontent.com/5043/158120132-1dfd9b4c-d3c4-410e-b7e1-34ccf604935e.png)

If I go into the internal link for the type, I can see its attributes:

![image](https://user-images.githubusercontent.com/5043/158120259-49bbaeb1-8599-4ffe-ab9e-0aa84e3ca73a.png)

**Comment by Gerrit0** [comment]
That's some odd output. Can you provide source code to run typedoc on that reproduces it?

**Comment by thelinuxlich** [comment]
Sure, was just testing:

```js
// @ts-check
/** @typedef { import("./types").Animal } Animal */

/** @type {string} */
let foo = "a"

/**
 *
 *
 * @param {Animal} foo
 * @param {*} bar
 */
let bar = (foo, bar) => "test"

/**
 *
 *
 * @param {*} test
 */
let biz = (test) => 123


/** @type {string} */
const b = "a"


/**
 * @param {*} begin
 * @param {*} end
 */
function calculateDaysBetweenDates(begin, end) { }

/** @type {Animal} */
let dog = {
    alive: true,
    hp: 1
}
```

And the types.ts file:

```ts
export type Animal = {
    hp: number,
    alive: boolean
}
```

**Comment by thelinuxlich** [comment]
I've created a repository with the code: https://github.com/thelinuxlich/test_jsdoc_ts

**Comment by Gerrit0** [comment]
I don't think I'm going to bother with JS projects for plugin unless someone else decides to improve support, it's a fraction of TypeDoc's users, and this plugin is also only used by a fraction of TypeDoc users...
