### ISSUE TITLE
Can I generate documentation for unexported functions?

### ISSUE THREAD

**Issue by user72356** [Gerrit0/typedoc-plugin-missing-exports#14]
I'm generating documentation for an app to be read internally (not a public lib) and I was hoping to include the non-exported functions as well. I thought this plugin was going to be it, but apparently it doesn't deal with functions at all. How should I go about that?

**Comment by Gerrit0** [comment]
This is intended to document things which should have been exported (since they are referenced by some exported value) but aren't.

It sounds like you want this to document *everything* declared, which it isn't meant to do...

**Comment by user72356** [comment]
The exported methods do call the non-exported methods which I want to document. So I guess that counts as a reference? If this is supposed to work then I'm clearly doing something wrong.

**Comment by Gerrit0** [comment]
> So I guess that counts as a reference?

No, a reference is like this:

```ts
export function foo(): Bar

// not exported, but referenced
type Bar = 123
```

**Comment by user72356** [comment]
I see what you mean. I'm afraid this project isn't going to cut it for me then. However, if anybody else is looking for something similar to what I described, I just found this project which in my tests appears to work quite well for this purpose: https://github.com/SoftwareBrothers/better-docs
