### ISSUE TITLE
Symbol didn't get documented if imported without reassigning

### ISSUE THREAD

**Issue by davidyuk** [Gerrit0/typedoc-plugin-missing-exports#15]
I have a module:
```ts
import f1 from './file';
export type F = typeof f1;
```
when I'm building documentation for it I'm getting a warning:
```
./file.ts:1:0 - warning default is referenced by F but not included in the documentation.

1    export default {
```
If I'm adding a reassignment of imported module:
```ts
import _f1 from './file';
const f1 = _f1;
export type F = typeof f1;
```
then everything works fine.

Reproduction: https://github.com/davidyuk/reproductions/tree/typedoc-plugin-missing-exports

**Comment by Gerrit0** [comment]
This is specific to `export default`. Named exports work just fine.

... as usual, default exports are problematic.... oh how I wish they didn't exist...
