### ISSUE TITLE
Any way to include the missing exports in the JSON output too?

### ISSUE THREAD

**Issue by andcasa** [Gerrit0/typedoc-plugin-missing-exports#17]
The plugin works great and adds all the missing exports to the generated documentation, however, for my use case, I'd like to have the same in the JSON generated with `--json`. Is there any way to achieve that?

**Comment by Gerrit0** [comment]
They are included - the json output serializes everything in the project, so if you look for the module named `<internal>`, or whatever you set `internalModule` to, you'll see stuff added by this plugin.
