### ISSUE TITLE
Except namespace has All @internal tag when I use `excludeInternal`

### ISSUE THREAD

**Issue by woo-yu** [Gerrit0/typedoc-plugin-missing-exports#20]
Hi. This plugin is so useful for our work. thanks for making.
but, I propose... when missing-exports plugin make `internalNs`, I wanna delete it that has all `@internal` tags in children.

this code solve it.
```typescript
if (!internalNs.children?.length || isExcludeInternal()) {
    context.project.removeReflection(internalNs);
}

...

fun isExcludeInternal() {
  return context.converter.application.options.getValue("excludeInternal") && !internalNs.children.filter(child => !child.comment?.hasModifier("@internal"))?.length;
}
```

I hope to hear from you soon. thanks.

**Comment by Gerrit0** [comment]
I... don't understand what you are saying. I added a test which shows that this plugin respects `@internal`, so if everything attempted to be added by this plugin has `@internal`, the namespace will already automatically be removed...
