### ISSUE TITLE
Setting 'excludeExternals' doesn't exclude imports from other packages within monorepo

### ISSUE THREAD

**Issue by rgauselumifi** [Gerrit0/typedoc-plugin-missing-exports#26]
Hi there,

Thanks you for the great program, it's very useful. 

I'm using Turborepo, and generating documentation for multiple 'packages'. My goal is to have any members that haven't been exported, but are referenced, included in the documentation, which this plugin accomplishes. 

However, some of my packages import types from other local 'packages', which I'm already generating documentation for. I'd like the ability for this plugin to only generate documentation for members that are defined and referenced within the root directory only.

Setting 'excludeExternals' to true is removing types from 'React' for instance, but not for other internal packages within the monorepo. We're using this monorepo and documentation internally, so we're essentially trying to document everything in our monorepo. I've looked through some conversations regarding the difference in philosophy that Typedoc has in mind, so I'm open to ideas or better ways of handling this as well if you have any. 

Thanks a ton in advance, cheers.

**Comment by Gerrit0** [comment]
The excludeExternals options determines if something is external via the externalPattern option, https://github.com/TypeStrong/typedoc/issues/2354, so you should be able to use that to achieve what you want

**Comment by rgauselumifi** [comment]
Thank you for the update, I'm attempting to go in each package and set the 'externalPattern' to exclude anything under the 'packages' directory accept for the current package I'm in. Here's how I've configured it:

  "externalPattern": "**/packages/!(some-dir)/**"

This doesn't seem to exclude any directories when I do this, but if I set it to 

  "externalPattern": "**/packages/**" it will exclude everything under packages, including 'some-dir', which I don't want excluded. 
  
  Is my regex incorrect?

**Comment by rgauselumifi** [comment]
> Thank you for the update, I'm attempting to go in each package and set the 'externalPattern' to exclude anything under the 'packages' directory accept for the current package I'm in. Here's how I've configured it:
> 
> "externalPattern": "**/packages/!(some-dir)/**"
> 
> This doesn't seem to exclude any directories when I do this, but if I set it to
> 
> "externalPattern": "**/packages/**" it will exclude everything under packages, including 'some-dir', which I don't want excluded.
> 
> Is my regex incorrect?

I should add, in my ts files, imports from other internal packages are imported from a module like "@repo/some-dir", but adding "@repo/types" as an externalPattern doesn't seem to work, which is why I'm attempting to use "packages/some-dir", as that is what @repo/some-dir evaluates to

**Comment by Gerrit0** [comment]
This seems to work for me, at least with npm's support for monorepos, I'm not familiar with turborepo. https://github.com/Gerrit0/typedoc-packages-example/tree/missing-exports-26 shows how I set up the `wrapping-lib` example so that the packages plugin works as I believe you're expecting

**Comment by rgauselumifi** [comment]
> This seems to work for me, at least with npm's support for monorepos, I'm not familiar with turborepo. https://github.com/Gerrit0/typedoc-packages-example/tree/missing-exports-26 shows how I set up the `wrapping-lib` example so that the packages plugin works as I believe you're expecting

I followed your repo and it worked! Thank you my friend.
