### ISSUE TITLE
Hi, what's the meaning of `aren't exported ` and `referenced`? could you give an example? 

### ISSUE THREAD

**Issue by liaodalin19903** [Gerrit0/typedoc-plugin-missing-exports#28]
> Automatically document symbols which aren't exported but are referenced.

Hi, what's the meaning of `aren't exported ` and `referenced`? could you give an example?

**Comment by Gerrit0** [comment]
https://github.com/Gerrit0/typedoc-plugin-missing-exports/blob/main/test/packages/single-missing-export/index.ts

The return type isn't exported, but is referenced by the export.
